[SPARK-32832][SS] Use CaseInsensitiveMap for DataStreamReader/Writer options
This PR aims to fix indeterministic behavior on DataStreamReader/Writer options like the following.
```scala
scala> spark.readStream.format("parquet").option("paTh", "1").option("PATH", "2").option("Path", "3").option("patH", "4").option("path", "5").load()
org.apache.spark.sql.AnalysisException: Path does not exist: 1;
```

This will make the behavior deterministic.

Yes, but the previous behavior is indeterministic.

Pass the newly test cases.

Closes #29702 from dongjoon-hyun/SPARK-32832.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit 2f85f9516cfc33a376871cf27f9fb4ac30ecbed8)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>